import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "./components/common/Header";
import { Inter } from "next/font/google";
import Footer from "./components/common/Footer";
import { Provider } from "react-redux";
import CommonLayout from "./components/common/CommonLayout";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <CommonLayout>
          {/* <ToastContainer /> */}

          <Header />
          {children}
          <Footer />
        </CommonLayout>
      </body>
    </html>
  );
}
